config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('shop/', include('shop.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from .views import *
from django.urls import path, include

app_name = 'shop'

urlpatterns = [
    path('product_list/', product_list, name='product_list'),
    path('product_add', product_add, name='product_add'),
    path('product/<int:product_id>', product, name='product')
]

users/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('users_list/', users_list, name='users_list'),
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
]

shop/models.py
from django.db import models
from users.models import Seller

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name

class Product(models.Model):
    title=models.CharField(max_length=150)
    category=models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    description=models.TextField()
    image=models.ImageField(upload_to='Shope/product_imge/')
    stock_units=models.PositiveBigIntegerField(default=0)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    seller=models.ForeignKey(Seller, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    user_image = models.ImageField(
        blank=True,
        null=True,
        help_text='Фото профеля (400x400)',
        upload_to='user_image/',
    )
    USER_ROLE=(
        ('customer','Покупатель'),
        ('seller','Продовец')
    )
    role=models.CharField(max_length=20, choices=USER_ROLE, default='customer')
    phone_number=models.CharField(max_length=32)
    def is_customer(self):
        return self.role=='customer' or self.groups.filter(name='customer').exists()
    
    def is_seller(self):
        return self.role=='seller' or self.groups.filter(name='seller').exists()
    
    def __str__(self):
        return self.username
    
class Seller(models.Model):
    user=models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    rating=models.DecimalField(max_digits=3, decimal_places=2, default=0.0)
    balance=models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
    payout_details=models.JSONField(default=dict, blank=True)

    def __str__(self):
        return self.user.username

shop/forms.py
from PIL import Image
import string
from django import forms
from .models import *
from django.core.exceptions import ValidationError
import os


class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=('title','category','description','image','stock_units','price')
        exclude=('seller',)

    def clean_title(self):
        spec = string.punctuation
        title = self.cleaned_data.get('title')
        if spec in title:
            return ValidationError("В названии не должно быть спец символов")
        return title
    
    def clean_image(self):
        # image = Image.open(self.cleaned_data.get('image'))
        # if image.size > 5:
        #     return ValidationError("В названии не должно быть спец символов")
        image = self.cleaned_data.get('image')
        if image.size >= 5 * 1024 * 1024:
            return ValidationError("Файл должен весить менее 5 мб")
        return image
    
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 100:
            return ValidationError("минимальная цена 100")
        return price
        

users/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

class SignUpForm(forms.ModelForm):
    password1=forms.CharField(required=True, label='Password', widget=forms.PasswordInput())
    password2=forms.CharField(required=True, label='Confirm Password', widget=forms.PasswordInput())
    class Meta:
        model=CustomUser
        fields=('username','first_name','last_name','email', 'phone_number','user_image','password1','password2', 'role')

    def clean(self):
        cleaned = super().clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password1')
        if password1 != password2:
            return ValidationError("Пароли не совпадают")
        return cleaned
    
    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password1')
        if password:
            user.set_password(password)
        if commit:
            user.save()
            if user.role == 'seller':
                Seller.objects.create(user=user)
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'field'

class SignInForm(forms.ModelForm):
    class Meta:
        model=CustomUser
        fields=('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'field'

shop/views.py
from django.shortcuts import render
from .models import *
from .forms import ProductForm

# Create your views here.

def product_list(request):
    products = Product.objects.all()
    print(products)
    return render(request, 'product_list.html', {'products': products})

def product_add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return ProductForm('users_list')
    else:
        form = ProductForm()
    return render(request, 'product_add.html', {'form':form})



def product(request,product_id):
    print(product_id)
    prod = Product.objects.get(id=product_id)
    return render(request, 'product.html', {'product':prod})

users/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import SignUpForm, SignInForm

# Create your views here.

def users_list(request):
    users = CustomUser.objects.all()
    print(users)
    return render(request, 'users_list.html', {'users': users})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users_list')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form':form})

def signin(request):
    if request.method == 'POST':
        form = SignInForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            if CustomUser.objects.filter(username = username):
                pass
    else:
        form = SignInForm()
    return render(request, 'signin.html', {'form':form})

def signout(request):
    ...

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />    
  </head>
  <body>
    
    <div class="container mt-4">{% block content %}{% endblock content %}</div>
  </body>
</html>

shop/templates/product.html
{# product_list.html #}
{% extends "base.html" %}

{% block title %}Product List{% endblock title %}

{% block content %}
<h1>Product</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4">
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text"><strong>Price:</strong> ${{ product.price }}</p>
                    <p class="card-text"><strong>Stock Units:</strong> {{ product.stock_units }}</p>
                    <a href="{% url 'shop:product'  product.id  %}">Ссылкак на продукт</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

shop/templates/product_add.html
{# signup.html #}
{% extends "base.html" %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
  <h1>Add Product</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Add Product</button>
  </form>
{% endblock content %}

shop/templates/product_list.html
{# product_list.html #}
{% extends "base.html" %}

{% block title %}Product List{% endblock title %}

{% block content %}
  <h1>Product List</h1>
  <div class="row">
    {% for product in products %}
    <div class="col-md-4">
        <div class="card mb-4">
            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><strong>Price:</strong> ${{ product.price }}</p>
                <p class="card-text"><strong>Stock Units:</strong> {{ product.stock_units }}</p>
                <a href="{% url 'shop:product'  product.id  %}">Ссылкак на продукт</a>
            </div>
        </div>
    </div>
{% endfor %}
</div>
</div>
{% endblock content %}

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />    
  </head>
  <body>
    <header>

    </header>
    <main class="container mt-4">
      {% block content %}{% endblock content %}
    </main>

    <footer>
      
    </footer>
  </body>
</html>

users/templates/signin.html
{# signup.html #}
{% extends "base.html" %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
  <h1>Sign In user</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sign In</button>
  </form>
{% endblock content %}

users/templates/signup.html
{# signup.html #}
{% extends "base.html" %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
  <h1>Sign Up</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
{% endblock content %}

users/templates/user_profile.html
{% extends "base.html" %}
<title>{% block title %} Профиль {{user.username}} {% endblock %}</title>
{% block content %}
    <img src="{{user.image.url}}" alt="" width="400" height="400">
    <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
    <p class="card-text"><strong>First Name:</strong> {{ user.first_name }}</p>
    <p class="card-text"><strong>Last Name:</strong> {{ user.last_name }}</p>
    <p class="card-text"><strong>Bio:</strong> {{ user.role }}</p>
    <p class="card-text"><strong>Number-phone:</strong> {{ user.phone_number }}</p>
    <form action="url 'users:delete_profile' user.id" method="post">
        {% csrf_token %}
        <button type="submit">Delete profile</button>
    </form> 
{% endblock %}

users/templates/users_list.html
{# product_list.html #}
{% extends "base.html" %}

{% block title %}Product List{% endblock title %}

{% block content %}
  <h1>User List</h1>
  <div class="row">
    {% for user in users %}
    <div class="col-md-4">
        <div class="card mb-4">
          {% if user.user_image %}
            <img src="{{ user.user_image.url }}" class="card-img-top" alt="{{ user.username }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ user.username }}</h5>
                <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
                <p class="card-text"><strong>First Name:</strong> {{ user.first_name }}</p>
                <p class="card-text"><strong>Last Name:</strong> {{ user.last_name }}</p>
                <p class="card-text"><strong>Bio:</strong> {{ user.role }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}